plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
}

version = project.mod_version
group = 'com.example'
base { archivesName = 'hitdistance' }

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

tasks.withType(JavaCompile).configureEach { options.release = 21 }
java { withSourcesJar() }
